;==========================================================================
; Font index exported lun. nov. 29 2010 by FontIO.cpp 57 2010-11-24 23:24:47Z gascuel $ 
;==========================================================================
aa_font90_chars		EQU	.12
aa_font90_firstChar	EQU	'.'
aa_font90_lastChar	EQU	'9'
;
aa_font90_idx:
			DW	aa_font90_bits + 0x0000	; . dot
			DW	aa_font90_bits + 0x0017	; / slash
			DW	aa_font90_bits + 0x002A	; 0 0
			DW	aa_font90_bits + 0x0110	; 1 1
			DW	aa_font90_bits + 0x018A	; 2 2
			DW	aa_font90_bits + 0x0265	; 3 3
			DW	aa_font90_bits + 0x034E	; 4 4
			DW	aa_font90_bits + 0x03E6	; 5 5
			DW	aa_font90_bits + 0x049C	; 6 6
			DW	aa_font90_bits + 0x05AB	; 7 7
			DW	aa_font90_bits + 0x0652	; 8 8
			DW	aa_font90_bits + 0x0784	; 9 9
			DW	aa_font90_bits + 0x0898	; END OF INDEX
