;==========================================================================
; Font index exported by fontconv.php 1.00 2011-08-13 03:38:31 rvs $
;==========================================================================
aa_font48_chars		EQU	.17
aa_font48_firstChar	EQU	'.'
aa_font48_lastChar	EQU	'>'
;
aa_font48_idx:
			DW	aa_font48_bits+0x0000	; . dot
			DW	aa_font48_bits+0x0014	; / slash
			DW	aa_font48_bits+0x001A	; 0 0
			DW	aa_font48_bits+0x00A3	; 1 1
			DW	aa_font48_bits+0x00ED	; 2 2
			DW	aa_font48_bits+0x0176	; 3 3
			DW	aa_font48_bits+0x0204	; 4 4
			DW	aa_font48_bits+0x0260	; 5 5
			DW	aa_font48_bits+0x02D2	; 6 6
			DW	aa_font48_bits+0x037F	; 7 7
			DW	aa_font48_bits+0x03EB	; 8 8
			DW	aa_font48_bits+0x04AB	; 9 9
			DW	aa_font48_bits+0x0557	; : colon
			DW	aa_font48_bits+0x0582	; ; semicolon
			DW	aa_font48_bits+0x05A5	; < less
			DW	aa_font48_bits+0x05D9	; = equal
			DW	aa_font48_bits+0x0625	; > greater
			DW	aa_font48_bits+0x062B	; END OF INDEX
